export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  QUEUED: 'QUEUED',
  SUBMITTING: 'SUBMITTING',
  SUBMITTED: 'SUBMITTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type InvoiceStatus =
  (typeof INVOICE_STATUS)[keyof typeof INVOICE_STATUS];

export const EVENT_TYPE = {
  INVOICE_CREATED: 'INVOICE_CREATED',
  VALIDATION_PASSED: 'VALIDATION_PASSED',
  SUBMISSION_QUEUED: 'SUBMISSION_QUEUED',
  SUBMISSION_STARTED: 'SUBMISSION_STARTED',
  SUBMISSION_SUCCEEDED: 'SUBMISSION_SUCCEEDED',
  SUBMISSION_FAILED: 'SUBMISSION_FAILED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  STATUS_RECONCILED: 'STATUS_RECONCILED',
  REQUEUE_REQUESTED: 'REQUEUE_REQUESTED',
} as const;

export const INVOICE_QUEUE_NAME = 'invoice-submission';
export const INVOICE_SUBMISSION_JOB = 'submit-invoice';
export const WEBHOOK_QUEUE_NAME = 'outbound-webhooks';
export const WEBHOOK_DELIVERY_JOB = 'deliver-webhook';
